/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

const _deepseek_ai_dsh_draco_seedance_gen_dracoVideoClip_readVideoClip_parameter_0$schema = z.string()
const _deepseek_ai_dsh_draco_seedance_gen_dracoVideoClip_readVideoClip_result$schema = z.union([z.object({
  'status': z.literal("ok"),
  'name': z.string(),
  'mediaType': z.literal("video/mp4"),
  'bytes': z.number(),
  'data': z.string(),
}), z.object({
  'status': z.literal("error"),
})])

export const TYPERT = {
  package: 'draco-seedance-gen',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: 'draco-seedance-gen#dracoVideoClip/readVideoClip',
      service: 'dracoVideoClip',
      namespace: 'dracoVideoClip',
      method: 'readVideoClip',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'name',
          wire: 'name',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'draco-seedance-gen#dracoVideoClip/readVideoClip:name',
            schema: _deepseek_ai_dsh_draco_seedance_gen_dracoVideoClip_readVideoClip_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'draco-seedance-gen/types#VideoClipView',
        schema: _deepseek_ai_dsh_draco_seedance_gen_dracoVideoClip_readVideoClip_result$schema,
      },
      sourceLocation: {"file":"packages/draco/draco-seedance-gen/src/remote.ts","line":26,"column":3},
    },
  ],
  model: {
    "services": [],
    "events": [],
    "objects": []
  },
}
