/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

const _deepseek_ai_dsh_draco_oauth_codex_codexOauthRemote_logout_result$schema = z.void()
const _deepseek_ai_dsh_draco_oauth_codex_codexOauthRemote_startLogin_result$schema = z.object({
  'status': z.union([z.literal("error"), z.literal("awaiting-approval"), z.literal("idle"), z.literal("active"), z.literal("expired")]),
  'verificationUri': z.string().optional(),
  'userCode': z.string().optional(),
  'error': z.string().optional(),
})
const _deepseek_ai_dsh_draco_oauth_codex_codexOauthRemote_status_result$schema = z.union([z.object({
  'kind': z.literal("idle"),
}), z.object({
  'kind': z.literal("awaiting-approval"),
  'verificationUri': z.string(),
  'userCode': z.string(),
  'expiresIn': z.number(),
  'startedAt': z.number(),
}), z.object({
  'kind': z.literal("active"),
  'expiresAt': z.number(),
}), z.object({
  'kind': z.literal("error"),
  'message': z.string(),
}), z.object({
  'kind': z.literal("expired"),
})])

export const TYPERT = {
  package: 'draco-codex-oauth',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: 'draco-codex-oauth#codexOauthRemote/logout',
      service: 'codexOauthRemote',
      namespace: 'codexOauthRemote',
      method: 'logout',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'draco-codex-oauth#codexOauthRemote/logout:result',
        schema: _deepseek_ai_dsh_draco_oauth_codex_codexOauthRemote_logout_result$schema,
      },
      sourceLocation: {"file":"packages/draco/draco-oauth-codex/src/remote.ts","line":63,"column":3},
    },
    {
      id: 'draco-codex-oauth#codexOauthRemote/startLogin',
      service: 'codexOauthRemote',
      namespace: 'codexOauthRemote',
      method: 'startLogin',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'draco-codex-oauth/types#CodexOauthLoginView',
        schema: _deepseek_ai_dsh_draco_oauth_codex_codexOauthRemote_startLogin_result$schema,
      },
      sourceLocation: {"file":"packages/draco/draco-oauth-codex/src/remote.ts","line":26,"column":9},
    },
    {
      id: 'draco-codex-oauth#codexOauthRemote/status',
      service: 'codexOauthRemote',
      namespace: 'codexOauthRemote',
      method: 'status',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'draco-codex-oauth/types#CodexOauthStatusView',
        schema: _deepseek_ai_dsh_draco_oauth_codex_codexOauthRemote_status_result$schema,
      },
      sourceLocation: {"file":"packages/draco/draco-oauth-codex/src/remote.ts","line":41,"column":3},
    },
  ],
  model: {
    "services": [],
    "events": [
      {
        "description": "Codex OAuth just became active after a successful device-code login. Image-generation config listens and defaults its provider to Codex `gpt-image-2` when the user has not already chosen a backend.",
        "summary": "Codex OAuth just became active after a successful device-code login.",
        "tags": [
          {
            "name": "param",
            "argument": "expiresAt",
            "comment": "- epoch milliseconds at which the new access token expires.",
            "text": "@param expiresAt - epoch milliseconds at which the new access token expires.\n     *"
          },
          {
            "name": "mode",
            "comment": "emit",
            "text": "@mode emit"
          }
        ],
        "jsDoc": "/**\n * Codex OAuth just became active after a successful device-code login.\n * Image-generation config listens and defaults its provider to Codex\n * `gpt-image-2` when the user has not already chosen a backend.\n * @param expiresAt - epoch milliseconds at which the new access token expires.\n * @mode emit\n */",
        "name": "draco/codex-oauth-ready",
        "mode": "emit",
        "signature": "'draco/codex-oauth-ready'(expiresAt: number): void"
      }
    ],
    "objects": []
  },
}
