/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

const _deepseek_ai_dsh_draco_oauth_xai_xaiOauthRemote_logout_result$schema = z.void()
const _deepseek_ai_dsh_draco_oauth_xai_xaiOauthRemote_startLogin_result$schema = z.object({
  'status': z.union([z.literal("error"), z.literal("awaiting-approval"), z.literal("idle"), z.literal("active"), z.literal("expired")]),
  'verificationUriComplete': z.string().optional(),
  'userCode': z.string().optional(),
  'error': z.string().optional(),
})
const _deepseek_ai_dsh_draco_oauth_xai_xaiOauthRemote_status_result$schema = z.union([z.object({
  'kind': z.literal("idle"),
}), z.object({
  'kind': z.literal("awaiting-approval"),
  'verificationUri': z.string(),
  'verificationUriComplete': z.string(),
  'userCode': z.string(),
  'expiresIn': z.number(),
  'startedAt': z.number(),
}), z.object({
  'kind': z.literal("active"),
  'expiresAt': z.number(),
}), z.object({
  'kind': z.literal("error"),
  'message': z.string(),
}), z.object({
  'kind': z.literal("expired"),
})])

export const TYPERT = {
  package: 'draco-grok-oauth',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: 'draco-grok-oauth#xaiOauthRemote/logout',
      service: 'xaiOauthRemote',
      namespace: 'xaiOauthRemote',
      method: 'logout',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'draco-grok-oauth#xaiOauthRemote/logout:result',
        schema: _deepseek_ai_dsh_draco_oauth_xai_xaiOauthRemote_logout_result$schema,
      },
      sourceLocation: {"file":"packages/draco/draco-oauth-xai/src/remote.ts","line":64,"column":3},
    },
    {
      id: 'draco-grok-oauth#xaiOauthRemote/startLogin',
      service: 'xaiOauthRemote',
      namespace: 'xaiOauthRemote',
      method: 'startLogin',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'draco-grok-oauth/types#XaiOauthLoginView',
        schema: _deepseek_ai_dsh_draco_oauth_xai_xaiOauthRemote_startLogin_result$schema,
      },
      sourceLocation: {"file":"packages/draco/draco-oauth-xai/src/remote.ts","line":26,"column":9},
    },
    {
      id: 'draco-grok-oauth#xaiOauthRemote/status',
      service: 'xaiOauthRemote',
      namespace: 'xaiOauthRemote',
      method: 'status',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'draco-grok-oauth/types#XaiOauthStatusView',
        schema: _deepseek_ai_dsh_draco_oauth_xai_xaiOauthRemote_status_result$schema,
      },
      sourceLocation: {"file":"packages/draco/draco-oauth-xai/src/remote.ts","line":41,"column":3},
    },
  ],
  model: {
    "services": [],
    "events": [
      {
        "description": "xAI OAuth just became usable: a successful device-code login, a persisted session loading from disk, or a successful token refresh. Image-generation config listens and defaults its provider to Grok Imagine when the user has not already chosen a backend.",
        "summary": "xAI OAuth just became usable: a successful device-code login, a persisted session loading from disk, or a successful token refresh.",
        "tags": [
          {
            "name": "param",
            "argument": "expiresAt",
            "comment": "- epoch milliseconds at which the new access token expires.",
            "text": "@param expiresAt - epoch milliseconds at which the new access token expires.\n     *"
          },
          {
            "name": "mode",
            "comment": "emit",
            "text": "@mode emit"
          }
        ],
        "jsDoc": "/**\n * xAI OAuth just became usable: a successful device-code login, a\n * persisted session loading from disk, or a successful token refresh.\n * Image-generation config listens and defaults its provider to Grok\n * Imagine when the user has not already chosen a backend.\n * @param expiresAt - epoch milliseconds at which the new access token expires.\n * @mode emit\n */",
        "name": "draco/xai-oauth-ready",
        "mode": "emit",
        "signature": "'draco/xai-oauth-ready'(expiresAt: number): void"
      }
    ],
    "objects": []
  },
}
